# NumPy Tutorial

In [1]:
import numpy as np
import sys
import time

## Advantages of using NumPy

There are three advantages of using NumPy Array over lists.
1) Less memory allocation
2) Less time complex
3) Comes with built-in features such as direct operations and useful functions

The following code snippet shows the difference in allocated memory to the list and NumPy array of the same size

In [2]:
ar = range(100000)
sizeofar = sys.getsizeof(1) * len(ar)

npar = np.arange(100000)
sizeofnpar = npar.size * npar.itemsize

print("Memory allocated to pythonn list:",sizeofar)
print("Memory allocated to pythonn list:",sizeofnpar)

Memory allocated to pythonn list: 2800000
Memory allocated to pythonn list: 400000


The following code snippet shows the difference in time taken to perform basic addition operation for two lists as well as two NumPy arrays. It also demonstrates how convenient it is to perform operations on NumPy arrays.

In [3]:
ls = range(100000)
ls2 = range(100000)
start_time = time.time()
resultls = list((x+y) for x,y in zip(ls,ls2))
time_taken = (time.time() - start_time) * 1000
print("Time taken to add two lists each of size 100000 in milliseconds:",time_taken)

arr = np.arange(100000)
arr2 = np.arange(100000)
start_time = time.time()
resultls = arr + arr2
time_taken = (time.time() - start_time) * 1000
print("Time taken to add two NumPy RRy each of size 100000 in milliseconds:",time_taken)

Time taken to add two lists each of size 100000 in milliseconds: 7.9708099365234375
Time taken to add two NumPy RRy each of size 100000 in milliseconds: 0.0


## Initializing NumPy arrays

In [4]:
# Single dimentional array
np1 = np.array([5,6,2,5,7,9,8,0])
print("Single Dimensional Array\n",np1)

# Two dimentional array
np2 = np.array([[5,6,2,5,7,9,8,0],[5,6,2,5,7,9,8,0],[5,6,2,5,7,9,8,0]])
print("Two Dimensional Array:\n",np2)

# Three dimentional array
np3 = np.array([[[5,6,2,5,7,9,8,0],[5,6,2,5,7,9,8,0]],[[5,6,2,5,7,9,8,0],[5,6,2,5,7,9,8,0]]])
print("Three Dimensional Array:\n",np3)

# Initializing an array of a specific type
np4 = np.array([1,2,3,4,5], dtype=float)
print("Array of float type:\n",np4)

# Initializing an array of a given shape and a specific type
np5 = np.ones(shape=(3,2), dtype=int)
print("Array of shape ",np5.shape," :\n",np5)

np6 = np.zeros(shape=(3,2), dtype=float)
print("Array of shape ",np6.shape," :\n",np6)

# Initializing an array with a range of numbers
np7 = np.arange(20)
print("Array containing the numbers from 0-19:\n",np7)

# Initializing an array with a number of elements in a given range having a common difference
np8 = np.arange(0,20,2)
print("Array containing the numbers from 0-19 with a common difference of 2:\n",np8)

# Initializing an array with a given number of elements in a given range having a common difference
np9 = np.linspace(0,20,30)
print("Array containing 30 elements between 0-19 with a common difference:\n",np9)

Single Dimensional Array
 [5 6 2 5 7 9 8 0]
Two Dimensional Array:
 [[5 6 2 5 7 9 8 0]
 [5 6 2 5 7 9 8 0]
 [5 6 2 5 7 9 8 0]]
Three Dimensional Array:
 [[[5 6 2 5 7 9 8 0]
  [5 6 2 5 7 9 8 0]]

 [[5 6 2 5 7 9 8 0]
  [5 6 2 5 7 9 8 0]]]
Array of float type:
 [1. 2. 3. 4. 5.]
Array of shape  (3, 2)  :
 [[1 1]
 [1 1]
 [1 1]]
Array of shape  (3, 2)  :
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Array containing the numbers from 0-19:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array containing the numbers from 0-19 with a common difference of 2:
 [ 0  2  4  6  8 10 12 14 16 18]
Array containing 30 elements between 0-19 with a common difference:
 [ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.310

## Some basic NumPy functions

In [5]:
# Printing the number of dimensions of a NumPy array
print(np3.ndim)

3


In [6]:
# Printing the shape of a NumPy array
print(np3.shape)

(2, 2, 8)


In [7]:
# Printing the size of an element in a NumPy array in bytes
print(np3.itemsize)

4


In [8]:
# Printing the size of a NumPy array (total number of elements in an array)
print(np3.size)

32


In [9]:
# Re-shaping an existing array
print("Original np7:\n",np7)
np7 = np7.reshape(5,4)
print("np7 after reshaping:\n",np7)

Original np7:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
np7 after reshaping:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [10]:
# Flatten an n dimentional array into a 1D array
np7 = np7.ravel()
print(np7)
np7 = np7.reshape(5,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## NumPy mathematical functions

In [11]:
# Fetching the smallest element in an array
print(np7.min())

0


In [12]:
# Fetching the largest element in an array
print(np7.max())

19


In [13]:
# Fetching the sum of all the elements of an array
print(np7.sum())

190


In [14]:
# Finiding minimum number accross an axis
print(np7.min(axis=0))

[0 1 2 3]


In [15]:
# Sum of all the elements accross an axis
print(np7.sum(axis=0))

[40 45 50 55]


In [16]:
# Square root of all the elements of an array
sqrt = np.sqrt(np7)
print(sqrt)

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894]]


In [17]:
# Standard deviation of the elements of an array
std = np7.std()
print(std)

5.766281297335398


## Stacking and Spliting NumPy arrays

In [18]:
# Stacking  
np8 = np.arange(20).reshape(4,5)
print("Array 1:\n",np8)

np9 = np.arange(20).reshape(4,5)
print("Array 2:\n",np9)

print("After horizontal stacking:\n",np.hstack((np8,np9)))

print("After vertical stacking:\n",np.vstack((np8,np9)))

Array 1:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Array 2:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
After horizontal stacking:
 [[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]]
After vertical stacking:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
# Vertical Splitting 

np10 = np.arange(50).reshape(5,10)
print("Original Array:\n",np10)

# Vertical Split
vspl = np.vsplit(np10,5)
print("After vsplit:")
i = 0
for ar in vspl:
    print("Array ", i, ":\n",ar)
    i+=1

Original Array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
After vsplit:
Array  0 :
 [[0 1 2 3 4 5 6 7 8 9]]
Array  1 :
 [[10 11 12 13 14 15 16 17 18 19]]
Array  2 :
 [[20 21 22 23 24 25 26 27 28 29]]
Array  3 :
 [[30 31 32 33 34 35 36 37 38 39]]
Array  4 :
 [[40 41 42 43 44 45 46 47 48 49]]


In [20]:
# Horizontal Split
hspl = np.hsplit(np10,2)
print("After hsplit:")
i = 0
for ar in hspl:
    print("Array ", i, ":\n",ar)
    i+=1

After hsplit:
Array  0 :
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
Array  1 :
 [[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]


## Indexing and Slicing

In [21]:
print("Two dimensional array:\n",np7)

Two dimensional array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [22]:
# Printing 3rd element of 2nd row and 3rd element of 3rd row using different notations
print(np7[1][2],",",np7[2,2]) 

6 , 10


In [23]:
# Printing 2nd complete row
print(np7[1,])

[4 5 6 7]


In [24]:
# Slicing a column (Will print 1st two elemetns of 2nd row)
print(np7[1,0:2])

[4 5]


In [25]:
# Slicing multiple columns (Will print 1st two elemetns of all the rows)
print(np7[0:,0:2])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]


In [26]:
# Slicing multiple rows (Will print 1st two rows)
print(np7[0:2,])

[[0 1 2 3]
 [4 5 6 7]]


In [27]:
# Printing last row
print(np7[-1,])

[16 17 18 19]


In [28]:
# Printing 2nd last element of 3rd row
print(np7[3,-2])

14


In [29]:
# Printing the last two columns of all the rows
print(np7[0:,-2:])

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


In [30]:
# NumPy array as indices

print("Original Array:\n",np7)

# Boolean Array
less_than_10 = np7 < 10

print(less_than_10)

# Elements in np7 array that are less than 10
print("Elements in the array that are less than 10:\n",np7[less_than_10])

# Replacing the elements lesser than 10 with a placeholder value
np7[less_than_10] = 100

print("New array:\n",np7)

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]
Elements in the array that are less than 10:
 [0 1 2 3 4 5 6 7 8 9]
New array:
 [[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]]


## NumPy Array Iteration

In [31]:
# Iterating through the elements of the array

# The following method is not pythonic
for i in np7:
    for j in i:
        print(j)

100
100
100
100
100
100
100
100
100
100
10
11
12
13
14
15
16
17
18
19


In [32]:
# Using NumPy ravel
for i in np7.ravel():
    print(i)

100
100
100
100
100
100
100
100
100
100
10
11
12
13
14
15
16
17
18
19


In [33]:
# Using NumPy flat
for i in np7.flat:
    print(i)

100
100
100
100
100
100
100
100
100
100
10
11
12
13
14
15
16
17
18
19


In [43]:
# Using nditer to iterate elements in an array
for i in np.nditer(np7):
    print(i)

100
100
100
100
100
100
100
100
100
100
10
11
12
13
14
15
16
17
18
19


In [44]:
# Using nditer to iterate elements in Fortan style (column order)
for i in np.nditer(np7,order = 'F'):
    print(i)

100
100
100
12
16
100
100
100
13
17
100
100
10
14
18
100
100
11
15
19


In [45]:
# Using nditer to print elements from more than an array simultaneously
for i,j in np.nditer([np8,np9]):
    print(i,"\t",j)

0 	 0
1 	 1
2 	 2
3 	 3
4 	 4
5 	 5
6 	 6
7 	 7
8 	 8
9 	 9
10 	 10
11 	 11
12 	 12
13 	 13
14 	 14
15 	 15
16 	 16
17 	 17
18 	 18
19 	 19
